apiVersion: v1
kind: Secret
metadata:
  name: database
stringData:
  SPRING_DATASOURCE_URL: jdbc:mysql://pdb-mysql/petclinic
  SPRING_DATASOURCE_USERNAME: petclinic
  SPRING_DATASOURCE_PASSWORD: <+secrets.getValue("mysql_password")>
