# ---------------------------
# Visits Deployment
# ---------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: visits
  labels:
    app: petclinic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: petclinic
      tier: visits
  template:
    metadata:
      labels:
        app: petclinic
        tier: visits
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/actuator/prometheus"
        prometheus.io/port:  "8080"
    spec:
      containers:
        - name: app
          image: areger55/harness-se-lab-dockerhub-repo:visits-latest
          imagePullPolicy: Always
          resources:
            requests:
              memory: 256Mi
            limits:
              memory: 512Mi
          envFrom:
            - configMapRef:
                name: app
            - secretRef:
                name: database
            - configMapRef:
                name: app-wavefront
                optional: true
            - secretRef:
                name: app-wavefront
                optional: true
          env:
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: mysql-password
                  name: pdb-mysql
          ports:
            - name: http
              containerPort: 8080
          livenessProbe:
            httpGet:
              port: http
              path: /actuator/health/liveness
            initialDelaySeconds: 60
            timeoutSeconds: 4
          readinessProbe:
            httpGet:
              port: http
              path: /actuator/health/readiness
            initialDelaySeconds: 60
            timeoutSeconds: 4
---
# ---------------------------
# Visits Service
# ---------------------------
apiVersion: v1
kind: Service
metadata:
  name: visits
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: http
  selector:
    app: petclinic
    tier: visits
