---
apiVersion: v1
kind: Service
metadata:
  name: app-lb-dev
  namespace: petclinic-dev
  labels:
    app: petclinic
    tier: api-gateway
    env: dev
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
  selector:
    app: petclinic
    tier: api-gateway
---
apiVersion: v1
kind: Service
metadata:
  name: app-lb-stg
  namespace: petclinic-stg
  labels:
    app: petclinic
    tier: api-gateway
    env: stg
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
  selector:
    app: petclinic
    tier: api-gateway
---
apiVersion: v1
kind: Service
metadata:
  name: app-lb-prd
  namespace: petclinic-prd
  labels:
    app: petclinic
    tier: api-gateway
    env: prd
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
  selector:
    app: petclinic
    tier: api-gateway
